CleverIt\UBL\Invoice\RO\ChipApplicationID:
    xml_root_name: ChipApplicationID
    xml_root_namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
    namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
