CleverIt\UBL\Invoice\RO\EnvironmentalEmissionType:
    properties:
        environmentalEmissionTypeCode:
            expose: true
            access_type: public_method
            serialized_name: EnvironmentalEmissionTypeCode
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getEnvironmentalEmissionTypeCode
                setter: setEnvironmentalEmissionTypeCode
            type: CleverIt\UBL\Invoice\RO\EnvironmentalEmissionTypeCode
        valueMeasure:
            expose: true
            access_type: public_method
            serialized_name: ValueMeasure
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getValueMeasure
                setter: setValueMeasure
            type: CleverIt\UBL\Invoice\RO\ValueMeasure
        description:
            expose: true
            access_type: public_method
            serialized_name: Description
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getDescription
                setter: setDescription
            xml_list:
                inline: true
                entry_name: Description
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            type: array<CleverIt\UBL\Invoice\RO\Description>
        emissionCalculationMethod:
            expose: true
            access_type: public_method
            serialized_name: EmissionCalculationMethod
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getEmissionCalculationMethod
                setter: setEmissionCalculationMethod
            xml_list:
                inline: true
                entry_name: EmissionCalculationMethod
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<CleverIt\UBL\Invoice\RO\EmissionCalculationMethod>
